/**
 * Curated LA restaurant list with editorial signals.
 * Used to enrich Google Places results with real metadata when names match.
 * Sources: Infatuation, Eater LA, Michelin Guide, LA Times, James Beard, local knowledge.
 */

export interface CuratedEntry {
  name: string
  neighborhood: string
  cuisine: string
  price: 1 | 2 | 3 | 4
  vibe: string[]
  whyGo: string
  knownFor: string
  goodFor: string[]
  signals: string[]
  confidence: 'high' | 'medium'
  editorialScore: number // 1–100
}

export const CURATED_LA: CuratedEntry[] = [

  // ── Arts District / DTLA ─────────────────────────────────────────────────
  {
    name: 'Bestia',
    neighborhood: 'Arts District',
    cuisine: 'Italian',
    price: 3,
    vibe: ['Buzzy', 'Date night', 'Chef-driven'],
    whyGo: 'Ori Menashe\'s pasta and charcuterie program is as good as it gets in LA. Still one of the hardest reservations in the city for a reason.',
    knownFor: 'Uni cacio e pepe, house-cured meats, beef heart ragù',
    goodFor: ['Date night', 'Special occasion', 'Celebration'],
    signals: ['Michelin', 'Infatuation', 'Eater LA', 'LA Times', 'James Beard Nominated'],
    confidence: 'high',
    editorialScore: 96,
  },
  {
    name: 'Bavel',
    neighborhood: 'Arts District',
    cuisine: 'Middle Eastern',
    price: 3,
    vibe: ['Buzzy', 'Date night', 'Chef-driven'],
    whyGo: 'From the Bestia team — hummus with braised lamb, wood-fired breads, and cocktails that actually make sense with the food. A genuine destination.',
    knownFor: 'Duck basteeya, hummus with braised lamb, malabi',
    goodFor: ['Date night', 'Special occasion', 'Group dinner'],
    signals: ['Michelin', 'Infatuation', 'Eater LA', 'LA Times', 'James Beard Winner'],
    confidence: 'high',
    editorialScore: 97,
  },
  {
    name: 'Manuela',
    neighborhood: 'Arts District',
    cuisine: 'Southern Californian',
    price: 3,
    vibe: ['Laid-back cool', 'Neighborhood go-to', 'Artsy'],
    whyGo: 'Inside Hauser & Wirth gallery — but don\'t let that fool you. The food is seriously good Southern-inflected California cooking with a great bar program.',
    knownFor: 'Fried chicken, smoked brisket, seasonal vegetable sides',
    goodFor: ['Weekend lunch', 'Date night', 'After gallery visits'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 88,
  },
  {
    name: 'Guerrilla Tacos',
    neighborhood: 'Arts District',
    cuisine: 'Mexican',
    price: 2,
    vibe: ['Casual', 'Chef-driven', 'Laid-back cool'],
    whyGo: 'Wes Avila trained at Bastide and now makes arguably the most creative tacos in LA. Sweet potato with almond chile, uni, sea urchin — this is serious cooking.',
    knownFor: 'Sweet potato taco, uni taco, ceviche',
    goodFor: ['Casual lunch', 'Quick dinner'],
    signals: ['Infatuation', 'Eater LA', 'James Beard Nominated'],
    confidence: 'high',
    editorialScore: 90,
  },
  {
    name: 'Rossoblu',
    neighborhood: 'DTLA',
    cuisine: 'Italian',
    price: 3,
    vibe: ['Date night', 'Polished', 'Chef-driven'],
    whyGo: 'Chef Steve Samson\'s love letter to Bologna — some of the best handmade pasta and salumi in the city, in an airy space that feels genuinely transportive.',
    knownFor: 'Tagliatelle al ragù, tigelle, cotechino',
    goodFor: ['Date night', 'Business dinner', 'Special occasion'],
    signals: ['Michelin', 'Infatuation', 'Eater LA'],
    confidence: 'high',
    editorialScore: 89,
  },
  {
    name: 'Orsa & Winston',
    neighborhood: 'DTLA',
    cuisine: 'Japanese-Italian',
    price: 3,
    vibe: ['Chef-driven', 'Intimate', 'Date night'],
    whyGo: 'Josef Centeno\'s omakase-style Japanese-Italian concept is one of downtown\'s most interesting and personal restaurants. The bar is excellent too.',
    knownFor: 'Tasting menus, Japanese-Italian pasta, sake selection',
    goodFor: ['Special occasion', 'Date night'],
    signals: ['Michelin', 'Infatuation', 'Eater LA'],
    confidence: 'high',
    editorialScore: 88,
  },
  {
    name: 'Broken Spanish',
    neighborhood: 'DTLA',
    cuisine: 'Mexican',
    price: 3,
    vibe: ['Chef-driven', 'Date night', 'Buzzy'],
    whyGo: 'Ray Garcia\'s elevated take on Mexican cooking — carnitas that\'ll ruin other carnitas for you, masa dishes you won\'t find anywhere else, serious cocktails.',
    knownFor: 'Carnitas, masa-based dishes, agave spirits program',
    goodFor: ['Date night', 'Special occasion'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 88,
  },
  {
    name: 'Redbird',
    neighborhood: 'DTLA',
    cuisine: 'Modern American',
    price: 3,
    vibe: ['Stunning space', 'Date night', 'Polished'],
    whyGo: 'In the old rectory of a cathedral — the space alone is worth it, but Neal Fraser\'s cooking holds its own. Great for a proper date night with cocktails.',
    knownFor: 'Octopus, heritage pork, architectural space',
    goodFor: ['Date night', 'Special occasion', 'Business dinner'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 85,
  },

  // ── Mid-City / Fairfax / Beverly Grove ───────────────────────────────────
  {
    name: 'Jon & Vinny\'s',
    neighborhood: 'Fairfax',
    cuisine: 'Italian-American',
    price: 2,
    vibe: ['Neighborhood go-to', 'Casual', 'Always packed'],
    whyGo: 'The most beloved casual Italian in LA. Perfect pizza, excellent pasta, and a wine list that punches above its price. Go on a weeknight if you don\'t have a reservation.',
    knownFor: 'Panna pizza, chicken parm, soft serve, Calabrian chili pasta',
    goodFor: ['Casual dinner', 'Date night', 'Any occasion'],
    signals: ['Michelin Bib Gourmand', 'Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 94,
  },
  {
    name: 'Osteria Mozza',
    neighborhood: 'Hollywood',
    cuisine: 'Italian',
    price: 3,
    vibe: ['Classic', 'Chef-driven', 'Date night'],
    whyGo: 'Nancy Silverton\'s mozzarella bar remains a landmark. The burrata, fresh pasta, and wine program set the standard. One of the restaurants that made LA a serious food city.',
    knownFor: 'Mozzarella bar, burrata, orecchiette with sausage',
    goodFor: ['Date night', 'Special occasion', 'Business dinner'],
    signals: ['Michelin', 'Infatuation', 'Eater LA', 'James Beard Winner'],
    confidence: 'high',
    editorialScore: 93,
  },
  {
    name: 'Chi Spacca',
    neighborhood: 'Hollywood',
    cuisine: 'Italian',
    price: 4,
    vibe: ['Chef-driven', 'Meat-focused', 'Date night'],
    whyGo: 'The Mozza empire\'s meat-focused room — bistecca that rivals anything in Florence, focaccia di recco that\'s the best thing you\'ll eat this year, and a serious amaro list.',
    knownFor: 'Bistecca fiorentina, focaccia di recco, in-house charcuterie',
    goodFor: ['Special occasion', 'Date night', 'Celebration'],
    signals: ['Michelin', 'Infatuation', 'Eater LA'],
    confidence: 'high',
    editorialScore: 92,
  },
  {
    name: 'Night + Market',
    neighborhood: 'West Hollywood',
    cuisine: 'Thai',
    price: 2,
    vibe: ['Casual', 'Chef-driven', 'Neighborhood go-to'],
    whyGo: 'Kris Yenbamroong makes the Thai food you didn\'t know you were missing — funky, sour, spicy, and deeply personal. Not pad Thai. Order the boat noodles.',
    knownFor: 'Boat noodles, crying tiger, nam khao tod, Thai iced tea',
    goodFor: ['Casual dinner', 'Date night'],
    signals: ['Michelin Bib Gourmand', 'Infatuation', 'Eater LA', 'LA Times', 'James Beard Nominated'],
    confidence: 'high',
    editorialScore: 95,
  },
  {
    name: 'Animal',
    neighborhood: 'Fairfax',
    cuisine: 'American',
    price: 3,
    vibe: ['Chef-driven', 'Buzzy', 'Meat-forward'],
    whyGo: 'Vinny Dotolo and Jon Shook\'s original restaurant — still one of the most influential in LA. Pork belly, lamb ribs, foie gras. Come hungry.',
    knownFor: 'Pork belly sandwiches, lamb ribs, pig ear salad',
    goodFor: ['Date night', 'Group dinner'],
    signals: ['Infatuation', 'Eater LA', 'LA Times', 'James Beard Nominated'],
    confidence: 'high',
    editorialScore: 88,
  },
  {
    name: 'Salt\'s Cure',
    neighborhood: 'West Hollywood',
    cuisine: 'American',
    price: 3,
    vibe: ['Neighborhood gem', 'Intimate', 'Chef-driven'],
    whyGo: 'The cure program is the best in LA — house-cured meats, whole animal cooking, and a short menu that changes with what\'s available. One of the most quietly excellent spots in the city.',
    knownFor: 'House-cured meats, pork chop, seasonal vegetables',
    goodFor: ['Date night', 'Casual dinner'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 87,
  },
  {
    name: 'Petit Trois',
    neighborhood: 'Hollywood',
    cuisine: 'French',
    price: 2,
    vibe: ['Date night', 'Casual French', 'No-reservations'],
    whyGo: 'Ludo Lefebvre\'s tiny French counter is one of the most satisfying meals in LA. Omelette, steak frites, croque monsieur — executed so well it makes you question everything else.',
    knownFor: 'French omelette, steak frites, croque monsieur, martinis',
    goodFor: ['Date night', 'Casual dinner', 'Late night'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 91,
  },

  // ── West Hollywood ────────────────────────────────────────────────────────
  {
    name: 'Horses',
    neighborhood: 'West Hollywood',
    cuisine: 'Modern American',
    price: 3,
    vibe: ['Scene-y', 'Date night', 'Buzzy'],
    whyGo: 'The most talked-about restaurant in WeHo right now — Will Aghajanian\'s neo-diner cooking is genuinely great, the space is stunning, and the bar is one of the best in the city.',
    knownFor: 'Beef tartare, chicken under a brick, soft serve',
    goodFor: ['Date night', 'Birthday', 'Special occasion'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 93,
  },
  {
    name: 'Republique',
    neighborhood: 'Mid-City',
    cuisine: 'French Californian',
    price: 3,
    vibe: ['Stunning space', 'Date night', 'Weekend brunch'],
    whyGo: 'Walter Manzke\'s stunning Chaplin-era space hosts some of the best French-Californian cooking in the city. Pastries in the morning, serious dinner at night.',
    knownFor: 'Croque madame, charcuterie, French onion soup, pastries',
    goodFor: ['Date night', 'Weekend brunch', 'Special occasion'],
    signals: ['Michelin', 'Infatuation', 'Eater LA', 'James Beard Winner'],
    confidence: 'high',
    editorialScore: 94,
  },

  // ── Santa Monica / Venice / West LA ──────────────────────────────────────
  {
    name: 'Rustic Canyon',
    neighborhood: 'Santa Monica',
    cuisine: 'Californian',
    price: 3,
    vibe: ['Neighborhood go-to', 'Chef-driven', 'Date night'],
    whyGo: 'Jeremy Fox\'s vegetable-focused cooking is some of the most thoughtful in LA. A neighborhood restaurant that could compete anywhere in the country.',
    knownFor: 'Seasonal vegetable dishes, house-milled grains, natural wine list',
    goodFor: ['Date night', 'Casual dinner', 'Special occasion'],
    signals: ['Michelin', 'Infatuation', 'Eater LA', 'James Beard Winner'],
    confidence: 'high',
    editorialScore: 93,
  },
  {
    name: 'Gjusta',
    neighborhood: 'Venice',
    cuisine: 'Deli / Bakery',
    price: 2,
    vibe: ['Casual', 'Laid-back cool', 'Daytime favorite'],
    whyGo: 'The best deli-bakery in LA, full stop. Cured fish, smoked meats, incredible pastries, grain bowls, and coffee — a true all-day essential from the Gjelina group.',
    knownFor: 'Smoked fish, grain bowls, pastries, cured meats',
    goodFor: ['Breakfast', 'Casual lunch', 'Picnic'],
    signals: ['Michelin Bib Gourmand', 'Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 93,
  },
  {
    name: 'Gjelina',
    neighborhood: 'Venice',
    cuisine: 'Californian',
    price: 3,
    vibe: ['Laid-back cool', 'Scene-y', 'Date night'],
    whyGo: 'One of the restaurants that defined the Venice vibe — wood-fired everything, great vegetables, cocktails, and a patio that feels like you\'re exactly where you should be.',
    knownFor: 'Wood-fired pizzas, charred vegetables, short rib, charcuterie',
    goodFor: ['Date night', 'Group dinner', 'Casual dinner'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 89,
  },
  {
    name: 'Felix',
    neighborhood: 'Venice',
    cuisine: 'Italian',
    price: 3,
    vibe: ['Chef-driven', 'Date night', 'Polished'],
    whyGo: 'Evan Funke hand-rolls pasta with a level of obsession that borders on performance art. The best tagliatelle in LA, possibly the best Italian outside Italy.',
    knownFor: 'Hand-rolled pasta, tagliatelle al ragù, tiramisu',
    goodFor: ['Date night', 'Special occasion'],
    signals: ['Michelin', 'Infatuation', 'Eater LA', 'LA Times', 'James Beard Nominated'],
    confidence: 'high',
    editorialScore: 95,
  },
  {
    name: 'Cassia',
    neighborhood: 'Santa Monica',
    cuisine: 'Southeast Asian',
    price: 3,
    vibe: ['Date night', 'Chef-driven', 'Buzzy'],
    whyGo: 'Bryant Ng\'s French-Vietnamese brasserie is one of the most complete restaurants in LA — bánh mì, pho, Southeast Asian clay pots, serious cocktails, and a stunning space.',
    knownFor: 'Kaya toast, pork belly bánh mì, Singapore black pepper crab',
    goodFor: ['Date night', 'Special occasion', 'Group dinner'],
    signals: ['Michelin Bib Gourmand', 'Infatuation', 'Eater LA', 'James Beard Nominated'],
    confidence: 'high',
    editorialScore: 92,
  },
  {
    name: 'Birdie G\'s',
    neighborhood: 'Santa Monica',
    cuisine: 'American',
    price: 3,
    vibe: ['Neighborhood go-to', 'Chef-driven', 'Comfortable'],
    whyGo: 'Jeremy Fox\'s comfort-focused second restaurant — fried chicken, clam chowder tots, really great cocktails. Everything you want when you want real food.',
    knownFor: 'Fried chicken, clam chowder tots, ice cream sandwiches',
    goodFor: ['Casual dinner', 'Date night'],
    signals: ['Infatuation', 'Eater LA', 'James Beard Nominated'],
    confidence: 'high',
    editorialScore: 88,
  },
  {
    name: 'Destroyer',
    neighborhood: 'Culver City',
    cuisine: 'Californian',
    price: 2,
    vibe: ['Artsy', 'Daytime favorite', 'Chef-driven'],
    whyGo: 'Jordan Kahn\'s brutalist daytime café adjacent to his Vespertine restaurant. The most precise, design-forward breakfast/lunch in LA — dishes that look like installations.',
    knownFor: 'Grain bowls, soft-boiled eggs, open-faced toasts, coffee',
    goodFor: ['Breakfast', 'Casual lunch', 'Solo dining'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 87,
  },

  // ── Koreatown ────────────────────────────────────────────────────────────
  {
    name: 'Park\'s BBQ',
    neighborhood: 'Koreatown',
    cuisine: 'Korean BBQ',
    price: 3,
    vibe: ['Group experience', 'Date night', 'Late night'],
    whyGo: 'Consistently considered the best Korean BBQ in LA — high-quality dry-aged beef, exceptional banchan, and attentive tableside service. A proper experience.',
    knownFor: 'Prime beef, dry-aged galbi, chadolbaegi, lunch specials',
    goodFor: ['Date night', 'Group dinner', 'Birthday', 'Late night'],
    signals: ['Infatuation', 'Eater LA', 'LA Times', 'Michelin Bib Gourmand'],
    confidence: 'high',
    editorialScore: 93,
  },
  {
    name: 'Soot Bull Jeep',
    neighborhood: 'Koreatown',
    cuisine: 'Korean BBQ',
    price: 2,
    vibe: ['Old-school', 'Authentic', 'No frills'],
    whyGo: 'Thirty-plus years and still the smoky, charcoal-grilled standard that everyone else chases. No fancy presentation — just excellent beef over real charcoal.',
    knownFor: 'Charcoal-grilled galbi, bulgogi, unmarinated beef cuts',
    goodFor: ['Casual dinner', 'Late night', 'Group dinner'],
    signals: ['Infatuation', 'Eater LA', 'LA Times', 'Local institution'],
    confidence: 'high',
    editorialScore: 88,
  },
  {
    name: 'Sun Nong Dan',
    neighborhood: 'Koreatown',
    cuisine: 'Korean',
    price: 2,
    vibe: ['Casual', 'Authentic', 'Late night'],
    whyGo: 'The galbi jjim (braised short rib) here is a religious experience — tender, deeply flavored, absurdly large. Their gamjatang is equally serious. Open late.',
    knownFor: 'Galbi jjim, gamjatang, ox bone soup',
    goodFor: ['Late night', 'Casual dinner', 'Cold weather'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 90,
  },
  {
    name: 'Kobawoo House',
    neighborhood: 'Koreatown',
    cuisine: 'Korean',
    price: 2,
    vibe: ['Old-school', 'No frills', 'Authentic'],
    whyGo: 'The bossam here — boiled pork belly wrapped in salted cabbage with kimchi and oysters — is arguably the definitive version in LA. A real neighborhood institution.',
    knownFor: 'Bossam, bindaetteok, pajeon',
    goodFor: ['Casual dinner', 'Group dinner'],
    signals: ['Infatuation', 'Eater LA', 'Local institution'],
    confidence: 'high',
    editorialScore: 86,
  },

  // ── San Gabriel Valley ────────────────────────────────────────────────────
  {
    name: 'Chengdu Taste',
    neighborhood: 'Alhambra',
    cuisine: 'Sichuan',
    price: 2,
    vibe: ['Authentic', 'Group experience', 'No frills'],
    whyGo: 'The most reviewed restaurant in the entire San Gabriel Valley for a reason — serious Sichuan cooking with a menu that rewards exploration. Don\'t miss the boiled fish.',
    knownFor: 'Boiled fish with sour cabbage, toothpick lamb, dumplings in chili oil',
    goodFor: ['Group dinner', 'Casual dinner'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 91,
  },
  {
    name: 'Sea Harbour',
    neighborhood: 'Rosemead',
    cuisine: 'Dim Sum',
    price: 3,
    vibe: ['Weekend brunch', 'Group experience', 'Authentic'],
    whyGo: 'Widely regarded as the best dim sum in LA — Hong Kong–style, cart service, and a level of quality that makes you understand why people drive from across the city.',
    knownFor: 'Har gow, siu mai, turnip cake, egg tarts, bbq pork buns',
    goodFor: ['Weekend brunch', 'Family dinner', 'Group dinner'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 92,
  },
  {
    name: 'Newport Seafood',
    neighborhood: 'San Gabriel',
    cuisine: 'Chinese Seafood',
    price: 3,
    vibe: ['Group experience', 'Authentic', 'Seafood-focused'],
    whyGo: 'Live seafood done right — lobster, crab, and fish prepared with as much care as anywhere in Hong Kong. The butter-and-garlic lobster over noodles is the must-order.',
    knownFor: 'Garlic butter lobster, Dungeness crab, live seafood',
    goodFor: ['Special occasion', 'Group dinner', 'Birthday'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 89,
  },
  {
    name: 'Szechuan Impression',
    neighborhood: 'Alhambra',
    cuisine: 'Sichuan',
    price: 2,
    vibe: ['Authentic', 'Casual', 'Worth the drive'],
    whyGo: 'More refined than most SGV Sichuan spots — the cumin lamb, cold noodles, and mala hot pot are executed at a high level. A regular for serious eaters.',
    knownFor: 'Cumin lamb, cold noodles, dan dan mian, mapo tofu',
    goodFor: ['Casual dinner', 'Group dinner'],
    signals: ['Infatuation', 'Eater LA'],
    confidence: 'high',
    editorialScore: 87,
  },
  {
    name: 'Holbox',
    neighborhood: 'South LA (Mercado La Paloma)',
    cuisine: 'Mexican Seafood',
    price: 2,
    vibe: ['Chef-driven', 'Casual', 'Unique'],
    whyGo: 'Gilberto Cetina Jr.\'s coastal Mexican seafood in a community market — tostadas, ceviches, and shellfish that are genuinely some of the best bites in the city.',
    knownFor: 'Tostada de jaiba, aguachile, smoked marlin tostada',
    goodFor: ['Casual lunch', 'Casual dinner', 'Unique experience'],
    signals: ['Infatuation', 'Eater LA', 'LA Times', 'James Beard Nominated'],
    confidence: 'high',
    editorialScore: 91,
  },

  // ── Silver Lake / Los Feliz ───────────────────────────────────────────────
  {
    name: 'Sqirl',
    neighborhood: 'Silver Lake',
    cuisine: 'Californian',
    price: 2,
    vibe: ['Instagram-famous', 'Brunch destination', 'Daytime'],
    whyGo: 'The ricotta toast and sorrel pesto rice bowl made Silver Lake a food destination. Still worth the line for the quality of the produce and preserves.',
    knownFor: 'Sorrel pesto rice bowl, ricotta toast, seasonal jams',
    goodFor: ['Weekend brunch', 'Breakfast', 'Daytime'],
    signals: ['Infatuation', 'Eater LA', 'LA Times', 'James Beard Nominated'],
    confidence: 'high',
    editorialScore: 86,
  },
  {
    name: 'Pine & Crane',
    neighborhood: 'Silver Lake',
    cuisine: 'Taiwanese',
    price: 2,
    vibe: ['Casual', 'Neighborhood go-to', 'Fast-casual done right'],
    whyGo: 'The best fast-casual Taiwanese in LA — dan dan mian, scallion pancake egg rolls, three-cup chicken. No frills, no reservations, no disappointment.',
    knownFor: 'Dan dan mian, three-cup chicken, scallion pancake egg rolls',
    goodFor: ['Casual lunch', 'Casual dinner', 'Quick meal'],
    signals: ['Infatuation', 'Eater LA'],
    confidence: 'high',
    editorialScore: 87,
  },
  {
    name: 'Botanica',
    neighborhood: 'Silver Lake',
    cuisine: 'Californian',
    price: 2,
    vibe: ['Neighborhood gem', 'Brunch spot', 'Laid-back'],
    whyGo: 'A love letter to vegetables and California produce — but with enough substance that you leave full and satisfied. One of the most pleasant rooms in Silver Lake.',
    knownFor: 'Vegetable-forward plates, weekend brunch, natural wine',
    goodFor: ['Weekend brunch', 'Casual dinner', 'Date night'],
    signals: ['Infatuation', 'Eater LA'],
    confidence: 'high',
    editorialScore: 84,
  },
  {
    name: 'L&E Oyster Bar',
    neighborhood: 'Silver Lake',
    cuisine: 'Seafood',
    price: 2,
    vibe: ['Date night', 'Wine bar', 'Neighborhood gem'],
    whyGo: 'Tiny Silver Lake seafood bar that feels like something you\'d find in a cooler city — raw bar, grilled fish, great wine, and a cozy room. A real gem.',
    knownFor: 'Oysters, clams casino, whole grilled fish, wine list',
    goodFor: ['Date night', 'Casual dinner', 'Happy hour'],
    signals: ['Infatuation', 'Eater LA'],
    confidence: 'high',
    editorialScore: 85,
  },

  // ── Highland Park / Eagle Rock ────────────────────────────────────────────
  {
    name: 'Quarter Sheets',
    neighborhood: 'Highland Park',
    cuisine: 'Pizza',
    price: 2,
    vibe: ['Neighborhood gem', 'Buzzy', 'Casual'],
    whyGo: 'The most exciting pizza in LA right now — Detroit-style with serious toppings and a team that clearly obsesses over every detail. Get there early or call ahead.',
    knownFor: 'Detroit-style pizza, seasonal toppings, smash burger',
    goodFor: ['Casual dinner', 'Date night', 'Takeout'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 90,
  },
  {
    name: 'CaCao Mexicatessen',
    neighborhood: 'Highland Park',
    cuisine: 'Mexican',
    price: 1,
    vibe: ['Neighborhood gem', 'Authentic', 'Casual'],
    whyGo: 'A Mexican deli that takes its craft seriously — tamales, tacos, house-made moles, and genuinely great tortas. A neighborhood essential that doesn\'t get enough attention outside HLP.',
    knownFor: 'Tamales, mole negro, tortas, tacos',
    goodFor: ['Casual lunch', 'Takeout', 'Quick meal'],
    signals: ['Infatuation', 'Eater LA', 'Local favorite'],
    confidence: 'medium',
    editorialScore: 83,
  },

  // ── Beverly Hills / Century City ──────────────────────────────────────────
  {
    name: 'Spago',
    neighborhood: 'Beverly Hills',
    cuisine: 'Californian',
    price: 4,
    vibe: ['Classic LA', 'Special occasion', 'Scene-y'],
    whyGo: 'Wolfgang Puck\'s flagship remains one of the most important restaurants in LA history — and it still delivers. The smoked salmon pizza and the Caesar are essential.',
    knownFor: 'Smoked salmon pizza, Caesar salad, Wiener schnitzel',
    goodFor: ['Special occasion', 'Birthday', 'Business dinner'],
    signals: ['Michelin', 'Infatuation', 'Eater LA', 'James Beard Winner', 'LA institution'],
    confidence: 'high',
    editorialScore: 88,
  },
  {
    name: 'Matsuhisa',
    neighborhood: 'Beverly Hills',
    cuisine: 'Japanese',
    price: 4,
    vibe: ['Classic', 'Special occasion', 'Chef-driven'],
    whyGo: 'The original Nobu — Nobuyuki Matsuhisa opened this in 1987 and everything that followed (globally) comes from here. Black cod with miso is still the benchmark.',
    knownFor: 'Black cod with miso, new-style sashimi, yellowtail jalapeño',
    goodFor: ['Special occasion', 'Date night', 'Business dinner'],
    signals: ['Michelin', 'Infatuation', 'LA Times', 'LA institution'],
    confidence: 'high',
    editorialScore: 89,
  },

  // ── Mexican / Tacos ───────────────────────────────────────────────────────
  {
    name: 'Mariscos Jalisco',
    neighborhood: 'East Los Angeles',
    cuisine: 'Mexican Seafood',
    price: 1,
    vibe: ['No frills', 'Authentic', 'Iconic'],
    whyGo: 'The fried shrimp taco here — crispy, stuffed with shrimp, avocado, and salsa — has been called the best taco in LA for 20 years. They\'re right.',
    knownFor: 'Fried shrimp tacos, aguachile, tostadas',
    goodFor: ['Casual lunch', 'Quick meal'],
    signals: ['Infatuation', 'Eater LA', 'LA Times', 'James Beard Winner', 'Local institution'],
    confidence: 'high',
    editorialScore: 92,
  },
  {
    name: 'Guisados',
    neighborhood: 'Boyle Heights',
    cuisine: 'Mexican',
    price: 1,
    vibe: ['Casual', 'Neighborhood go-to', 'Accessible'],
    whyGo: 'Braised meat tacos that set the standard in LA — mole negro, tinga, chicharrón en salsa verde. Small corn tortillas, each one a decision. Get the sampler.',
    knownFor: 'Braised meat tacos, mole negro, tinga sampler',
    goodFor: ['Casual lunch', 'Quick meal', 'Takeout'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 90,
  },
  {
    name: 'Taco María',
    neighborhood: 'Costa Mesa',
    cuisine: 'Mexican',
    price: 3,
    vibe: ['Chef-driven', 'Date night', 'Elevated Mexican'],
    whyGo: 'Carlos Salgado\'s elevated Mexican cooking is some of the most technically impressive in Southern California — masa, mole, and seasonal produce treated as fine dining ingredients.',
    knownFor: 'Tasting menu, masa dishes, mole negro, margaritas',
    goodFor: ['Special occasion', 'Date night'],
    signals: ['Michelin', 'Infatuation', 'Eater LA', 'James Beard Winner'],
    confidence: 'high',
    editorialScore: 94,
  },

  // ── Ramen / Japanese ──────────────────────────────────────────────────────
  {
    name: 'Tsujita',
    neighborhood: 'Sawtelle',
    cuisine: 'Japanese / Ramen',
    price: 2,
    vibe: ['Authentic', 'Worth the line', 'Casual'],
    whyGo: 'The tsukemen (dipping ramen) here is as good as anything you\'ll find outside Japan — rich, porky, deeply savory dipping broth. Lines form early and for good reason.',
    knownFor: 'Tsukemen, tonkotsu ramen, maze soba',
    goodFor: ['Casual lunch', 'Casual dinner'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 89,
  },
  {
    name: 'Shibumi',
    neighborhood: 'DTLA',
    cuisine: 'Japanese Kaiseki',
    price: 4,
    vibe: ['Intimate', 'Chef-driven', 'Special occasion'],
    whyGo: 'David Schlosser\'s omakase interpretations of Japanese kaiseki are some of the most thoughtful meals you can have in LA. Counter seating, serious wine, and total focus.',
    knownFor: 'Kaiseki-style courses, seasonal Japanese produce, sake pairings',
    goodFor: ['Special occasion', 'Date night', 'Milestone celebration'],
    signals: ['Michelin', 'Infatuation', 'Eater LA'],
    confidence: 'high',
    editorialScore: 91,
  },

  // ── Pizza ─────────────────────────────────────────────────────────────────
  {
    name: 'Pizzana',
    neighborhood: 'Brentwood',
    cuisine: 'Pizza',
    price: 2,
    vibe: ['Date night', 'Neighborhood go-to', 'Italian'],
    whyGo: 'Daniele Uditi\'s neo-Neapolitan pies are consistently among the best in the city — airy, charred, deeply flavored, with great pasta and cocktails to match.',
    knownFor: 'Neo-Neapolitan pizza, cacio e pepe pizza, pasta',
    goodFor: ['Date night', 'Casual dinner'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 88,
  },
  {
    name: 'Bianco',
    neighborhood: 'Grand Central Market',
    cuisine: 'Pizza',
    price: 2,
    vibe: ['Casual', 'Iconic', 'Pizza-focused'],
    whyGo: 'Chris Bianco\'s celebrated pies from Phoenix, now in LA — Wiseguy with wood roasted onion and fennel sausage is a masterclass in restraint. Worth every bit of the wait.',
    knownFor: 'Wiseguy pizza, Rosa pizza, Rosa bianco',
    goodFor: ['Casual dinner', 'Date night'],
    signals: ['Infatuation', 'Eater LA', 'James Beard Winner'],
    confidence: 'high',
    editorialScore: 92,
  },

  // ── Natural Wine / Bar-forward ─────────────────────────────────────────────
  {
    name: 'Bavel',
    neighborhood: 'Arts District',
    cuisine: 'Middle Eastern',
    price: 3,
    vibe: ['Date night', 'Buzzy', 'Chef-driven'],
    whyGo: 'Already listed — one of the most complete restaurants in LA.',
    knownFor: 'Duck basteeya, hummus, malabi',
    goodFor: ['Date night'],
    signals: ['Michelin', 'Infatuation', 'Eater LA'],
    confidence: 'high',
    editorialScore: 97,
  },

  // ── Newer / Buzzy ─────────────────────────────────────────────────────────
  {
    name: 'Anajak Thai',
    neighborhood: 'Sherman Oaks',
    cuisine: 'Thai',
    price: 2,
    vibe: ['Buzzy', 'Chef-driven', 'Neighborhood gem'],
    whyGo: 'Justin Pichetrungsi\'s family restaurant turned destination — some of the most vibrant Thai cooking in LA, with a wine list that somehow makes sense with pad kra pow.',
    knownFor: 'Pad kra pow, larb, tom kha, natural wine program',
    goodFor: ['Casual dinner', 'Date night'],
    signals: ['Michelin Bib Gourmand', 'Infatuation', 'Eater LA', 'LA Times', 'James Beard Nominated'],
    confidence: 'high',
    editorialScore: 93,
  },
  {
    name: 'Konbi',
    neighborhood: 'Echo Park',
    cuisine: 'Japanese',
    price: 2,
    vibe: ['Daytime', 'Precise', 'Worth seeking out'],
    whyGo: 'A Japanese convenience store concept taken seriously — egg salad sandwiches that are technically perfect, matcha soft serve, and a genuine attention to craft.',
    knownFor: 'Japanese egg salad sandwich, katsu sando, matcha soft serve',
    goodFor: ['Breakfast', 'Casual lunch', 'Quick meal'],
    signals: ['Infatuation', 'Eater LA', 'LA Times'],
    confidence: 'high',
    editorialScore: 87,
  },
  {
    name: 'Kismet',
    neighborhood: 'Los Feliz',
    cuisine: 'Middle Eastern',
    price: 2,
    vibe: ['Neighborhood gem', 'Daytime', 'Vegetable-forward'],
    whyGo: 'Sara Kramer and Sarah Hymanson\'s sunshine-filled restaurant is one of the most joyful places to eat in LA — produce-driven Middle Eastern–inspired food that always feels exactly right.',
    knownFor: 'Labneh, grain bowls, roasted vegetables, daily specials',
    goodFor: ['Weekend brunch', 'Casual lunch', 'Casual dinner'],
    signals: ['Infatuation', 'Eater LA', 'James Beard Nominated'],
    confidence: 'high',
    editorialScore: 87,
  },
  {
    name: 'Langer\'s Deli',
    neighborhood: 'MacArthur Park',
    cuisine: 'Jewish Deli',
    price: 2,
    vibe: ['LA institution', 'Classic', 'Worth seeking out'],
    whyGo: 'The #19 pastrami on rye has been called the best sandwich in America by more than one serious food writer. Hand-cut hot pastrami, rye bread made right. An LA essential.',
    knownFor: '#19 pastrami on rye, hot pastrami, matzo ball soup',
    goodFor: ['Casual lunch', 'LA pilgrimage'],
    signals: ['Infatuation', 'Eater LA', 'LA Times', 'James Beard Winner', 'LA institution'],
    confidence: 'high',
    editorialScore: 91,
  },
  {
    name: 'Bay Cities Italian Deli',
    neighborhood: 'Santa Monica',
    cuisine: 'Italian Deli',
    price: 1,
    vibe: ['LA institution', 'Casual', 'Worth the line'],
    whyGo: 'The Godmother sandwich — salami, capicola, mortadella, pepperoni — on housemade bread with the works. One of the most famous sandwiches in LA. Lines are real.',
    knownFor: 'The Godmother sandwich, imported Italian goods',
    goodFor: ['Casual lunch', 'Takeout', 'Picnic'],
    signals: ['Infatuation', 'Eater LA', 'LA Times', 'LA institution'],
    confidence: 'high',
    editorialScore: 89,
  },
]

// Normalize a name for fuzzy matching
export function normalizeName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[''`]/g, "'")
    .replace(/[^a-z0-9\s']/g, '')
    .replace(/\b(the|a|an|restaurant|cafe|bar|grill|kitchen|house|&|and)\b/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

// Try to find a curated entry matching a Google Places name
export function findCuratedMatch(placeName: string): CuratedEntry | null {
  const normalized = normalizeName(placeName)
  // Exact match first
  const exact = CURATED_LA.find(e => normalizeName(e.name) === normalized)
  if (exact) return exact
  // Partial match — curated name contained in place name or vice versa
  const partial = CURATED_LA.find(e => {
    const cn = normalizeName(e.name)
    return cn.length > 3 && (normalized.includes(cn) || cn.includes(normalized))
  })
  return partial || null
}

// Known chains and fast food to downrank
export const CHAIN_NAMES = new Set([
  'cheesecake factory', 'olive garden', 'red lobster', 'applebees', 'chilis', 'ihop',
  'dennys', 'mcdonalds', 'burger king', 'wendys', 'taco bell', 'chipotle',
  'panda express', 'panera', 'subway', 'starbucks', 'dunkin', 'in-n-out',
  'five guys', 'shake shack', 'jack in the box', 'carls jr', 'del taco',
  'pf changs', 'bjs restaurant', 'claim jumper', 'el torito',
  'marie callenders', 'sizzler', 'outback steakhouse', 'red robin',
  'fridays', 'tgi fridays', 'california pizza kitchen', 'buca di beppo',
  'romano macaroni grill', 'macaroni grill', 'yard house', 'buffalo wild wings',
  'wingstop', 'raising canes', 'popeyes', 'kfc', 'pizza hut', 'dominos',
  'little caesars', 'papa johns', 'fatburger', 'islands', 'sweetgreen',
  'tender greens', 'lemonade', 'rubios', 'wahoos', 'souplantation',
  'hometown buffet', 'golden corral', 'denny\'s', 'jack in the box',
  'norm\'s', 'norm s', 'benihana', 'nobu', 'mastros', 'fleming\'s',
  'morton\'s', 'ruth\'s chris', 'capital grille', 'seasons 52',
  'california dreaming', 'legacy grill', 'the palm', 'bonefish grill',
  'longhorn steakhouse', 'texas roadhouse', 'chick fil a', 'whataburger',
  'sonic', 'arby\'s', 'dairy queen', 'culvers', 'portillos',
])

export function isChain(name: string): boolean {
  const n = name.toLowerCase().replace(/[^a-z0-9\s]/g, '').trim()
  return CHAIN_NAMES.has(n) || Array.from(CHAIN_NAMES).some(c => n === c)
}
